export interface Project {
  num: string;
  slug: string;
  title: string;
  category: string;
  tags: string[];
  tools: { name: string }[];
  description: string;
  longDescription?: string;
  challenges?: string[];
  problems?: string[];
  features?: string[];
  image: string;
  live?: string;
  github?: string;
}

export const projectsData: Project[] = [
  {
    num: "01",
    slug: "five-fashion",
    title: "FIVE Fashion 3D",
    category: "MERN Website",
    tags: ["MERN", "Full Stack", "Dashboard", "E-Commerce", "React", "3D", "RTL/LTR"],
    tools: [
      { name: "React" },
      { name: "TypeScript" },
      { name: "Vite" },
      { name: "Tailwind CSS" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "i18next" },
      { name: "JWT" },
      { name: "Zod" },
      { name: "Redux Toolkit" },
      { name: "Three.js" },
      { name: "React Three Fiber" },
    ],
    description:
      "Luxury 3D Fashion E-Commerce Platform. Premium bilingual (AR/EN) fashion marketplace with immersive 3D experiences, dark/light themes, and modern MERN architecture.",
    longDescription:
      "FIVE Fashion (Auralis) is a production-ready luxury fashion e-commerce platform featuring immersive 3D product previews, full Arabic/English with RTL/LTR support, dark and light themes via design tokens, customer accounts, cart & wishlist, checkout, order management, admin dashboard for catalog and orders, product reviews, SEO (JSON-LD, sitemap, robots), and a polished design system with metallic identity.",
    features: [
      "Immersive 3D product previews (React Three Fiber)",
      "Full Arabic + English with RTL/LTR",
      "Dark & light themes via design tokens",
      "Auth + customer account & orders",
      "Cart, wishlist, and checkout flow",
      "Admin dashboard: catalog CRUD & order moderation",
      "Product reviews, SEO, and JSON-LD",
      "Rate limiting, JWT, Zod validation, Helmet",
    ],
    challenges: [
      "Integrating 3D experiences without hurting performance or accessibility",
      "Supporting full RTL layout and bilingual content across shop and admin",
      "Building a secure auth, cart, and order pipeline with JWT and validation",
      "Designing a consistent luxury design system with dark/light tokens",
    ],
    problems: [
      "Isolated 3D canvases and optimized Three.js usage for production",
      "Centralized i18n with i18next and direction-aware layouts",
      "JWT access/refresh, rate limits, Helmet, and Zod on the API",
      "Token-based theming and reusable UI primitives",
    ],
    image: "/assets/projects images multi devices/17.png",
    live: "https://five-fashion-client.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/five-fashion",
  },
  {
    num: "02",
    slug: "fixer-repair-center",
    title: "Fixer — Repair Center SaaS",
    category: "MERN SaaS Platform",
    tags: ["SaaS", "MERN", "Full Stack", "Dashboard", "React", "RTL/LTR"],
    tools: [
      { name: "React 18" },
      { name: "TypeScript" },
      { name: "Vite" },
      { name: "Tailwind CSS" },
      { name: "Redux Toolkit" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "JWT" },
      { name: "Zod" },
      { name: "i18next" },
      { name: "Framer Motion" },
      { name: "Recharts" },
      { name: "Cloudinary" },
      { name: "Helmet" },
    ],
    description:
      "Full-stack MERN platform for repair centers — device intake to warranty. Customers, tickets, technicians, inventory, quotations, invoices, QR tracking, appointments, reports, and production hardening with full AR/EN + RTL support.",
    longDescription:
      "Fixer is a production-ready repair center operations SaaS that models the real workflow from device intake through warranty. It covers customers & devices, repair tickets with status workflow, technicians and role-based permissions, spare parts inventory, quotations with customer approval, invoices & payments, public QR live tracking, appointments, analytics & reports, notifications, and activity logs.",
    features: [
      "End-to-end repair workflow: intake → diagnosis → repair → delivery → warranty",
      "Customers, devices, tickets, technicians, inventory, quotations, invoices",
      "Public QR live customer tracking page",
      "Appointments, reports & analytics, notifications",
      "Full Arabic + English with RTL/LTR",
      "Role-based staff permissions",
      "Production hardening: Helmet, CORS, rate limits",
      "Dashboard metrics, charts, activity feed",
    ],
    challenges: [
      "Modeling a complete operational repair workflow",
      "Supporting full RTL/LTR and bilingual UI",
      "Building role-based permissions across staff roles",
      "Production hardening",
    ],
    problems: [
      "Phased vertical-slice architecture",
      "Centralized i18n with i18next",
      "JWT auth and role checks",
      "Zod env validation, Helmet, rate limits",
    ],
    image: "/assets/projects images multi devices/18.png",
    live: "https://fixer-client.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/repair-center-management-SaaS",
  },
  {
    num: "03",
    slug: "aqarco",
    title: "Aqarco — عقاركو",
    category: "Real Estate Platform",
    tags: ["Full Stack", "Dashboard", "Next.js", "React", "Real Estate", "RTL/LTR"],
    tools: [
      { name: "Next.js 16" },
      { name: "React 19" },
      { name: "TypeScript" },
      { name: "Tailwind CSS v4" },
      { name: "MongoDB" },
      { name: "Mongoose" },
      { name: "next-intl" },
      { name: "jose (JWT)" },
      { name: "Zod" },
      { name: "bcryptjs" },
      { name: "Cloudinary" },
    ],
    description:
      "Premium bilingual (AR/EN) real estate platform for property sales, rentals, investments, hotels, resorts, and apartment booking — with role-based dashboards for buyers, owners, agents, and operators.",
    longDescription:
      "Aqarco (عقاركو) is a premium full-stack real estate platform built with Next.js 16 App Router and MongoDB.",
    features: [
      "Property listings: sale, rent, investment, hotel & resort stays",
      "Multi-role access: buyer, renter, investor, owner, agent, hotel operator, admin",
      "Full Arabic + English with RTL/LTR (next-intl)",
      "Discover, compare, favorites, and property detail pages",
      "Bookings inbox and investment workflows",
      "Owner/agent listing management",
      "Admin: users and properties moderation",
      "JWT auth (jose), Zod validation, Cloudinary-ready uploads",
    ],
    challenges: [
      "Supporting many user roles with different dashboards",
      "Building a unified product for sale, rent, investment, and hospitality",
      "Full RTL/LTR and bilingual content",
      "Keeping listing, booking, and investment flows consistent",
    ],
    problems: [
      "Role-based route protection and dashboard views",
      "Locale-aware App Router with next-intl",
      "Structured property model covering multiple listing types",
      "JWT sessions with jose + Zod",
    ],
    image: "/assets/projects images multi devices/19.png",
    live: "https://aqarco.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/real-estate-platform",
  },
  {
    num: "04",
    slug: "delta-news",
    title: "Delta News — دلتا نيوز",
    category: "MERN Website",
    tags: ["MERN", "Full Stack", "Dashboard", "SaaS", "React", "News", "RTL/LTR"],
    tools: [
      { name: "React 19" },
      { name: "TypeScript" },
      { name: "Vite" },
      { name: "Tailwind CSS" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "i18next" },
      { name: "JWT" },
      { name: "Zod" },
      { name: "Cloudinary" },
      { name: "Helmet" },
    ],
    description:
      "Multilingual News & Sports media SaaS platform with full Arabic/English UI, editorial public site, SEO, and an admin dashboard for content and roles.",
    longDescription:
      "Delta News is a production-oriented News & Media platform built with the MERN stack.",
    features: [
      "Editorial public site: hero, breaking ticker, trending, categories",
      "Full Arabic + English UI and content with /en and /ar URLs",
      "SEO: canonical, hreflang, Open Graph, JSON-LD, sitemap, robots",
      "Admin dashboard: articles, categories, analytics, roles",
      "Multilingual article editor",
      "JWT auth + role-based access",
      "Bookmarks API",
      "Rate limiting, Helmet, Zod validation",
    ],
    challenges: [
      "Supporting full RTL/LTR layouts and bilingual content",
      "Building a flexible multilingual article model",
      "Strong SEO for dual-language media",
      "Securing admin routes and APIs",
    ],
    problems: [
      "Centralized i18n with locale-aware routing",
      "Structured article schema with localized fields",
      "Server-generated sitemap/robots plus meta tags",
      "JWT + httpOnly cookies, Helmet, rate limits",
    ],
    image: "/assets/projects images multi devices/16.png",
    live: "https://deltanewsclient.vercel.app/ar",
    github: "https://github.com/mahmoudSElsebaey/delta-news-mern",
  },
  {
    num: "05",
    slug: "universal-booking-saas",
    title: "Universal Booking SaaS",
    category: "MERN Website",
    tags: ["SaaS", "MERN", "Full Stack", "Dashboard", "React", "RTL/LTR"],
    tools: [
      { name: "React" },
      { name: "TypeScript" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "Tailwind CSS" },
      { name: "i18next" },
      { name: "JWT" },
      { name: "Zod" },
      { name: "Cloudinary" },
      { name: "Recharts" },
    ],
    description:
      "A reusable and white-label booking management SaaS platform for businesses to manage services, staff, customers, schedules, and bookings.",
    longDescription:
      "Bookora is a production-ready white-label booking platform designed for clinics, salons, gyms, consultants, and more.",
    features: [
      "White-label design system",
      "Full Arabic + English with RTL/LTR",
      "Role-based access (Owner, Manager, Staff, Customer)",
      "Availability engine with conflict protection",
      "Booking flow (create, cancel, reschedule)",
      "Admin & Customer dashboards + analytics",
      "In-app notifications",
      "Reviews & ratings",
    ],
    challenges: [
      "Flexible multi-tenant availability engine",
      "Full RTL layout and bilingual content",
      "Role-based permissions",
      "White-label ready design system",
    ],
    problems: [
      "Transactional checks and slot locking",
      "Centralized i18n with direction-aware layouts",
      "JWT + HTTP-only cookies",
      "Reusable Tailwind tokens",
    ],
    image: "/assets/projects images multi devices/14.png",
    live: "https://universal-booking-saas-client.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/universal-booking-saas",
  },
  {
    num: "06",
    slug: "e-commerce-full-stack",
    title: "Volt Store — فولت ستور",
    category: "MERN Website",
    tags: ["MERN", "Full Stack", "Dashboard", "E-Commerce", "React", "RTL/LTR"],
    tools: [
      { name: "React" },
      { name: "TypeScript" },
      { name: "Bootstrap" },
      { name: "Swiper" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "i18next" },
      { name: "Stripe" },
      { name: "PayPal" },
      { name: "Google Auth" },
      { name: "Zod" },
      { name: "Cloudinary" },
    ],
    description:
      "A full-stack MERN e-commerce application with authentication, payments, multi-language support, and product management.",
    longDescription:
      "A complete electronics e-commerce platform with product catalog, cart, checkout, payment gateways, admin dashboard, and multi-language support.",
    features: [
      "Full authentication & authorization",
      "Stripe & PayPal payments",
      "Multi-language support",
      "Admin product management",
      "Cloudinary image uploads",
    ],
    challenges: [
      "Integrating multiple payment providers securely",
      "Handling cart state and order consistency",
      "Building an admin flow for catalog management",
    ],
    problems: [
      "Separated payment adapters and webhook handling",
      "Validated orders with Zod and server-side checks",
      "Structured admin APIs for CRUD operations",
    ],
    image: "/assets/projects images multi devices/1.png",
    live: "https://electric-store-mern.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/electric-store-mern",
  },
  {
    num: "07",
    slug: "examflow",
    title: "ExamFlow — SaaS MVP",
    category: "SaaS / EdTech MVP",
    tags: ["SaaS", "MVP", "MERN", "Full Stack", "Dashboard", "React", "RTL/LTR"],
    tools: [
      { name: "React" },
      { name: "TypeScript" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "Tailwind CSS" },
      { name: "i18next" },
      { name: "JWT" },
      { name: "Stripe" },
      { name: "Resend" },
      { name: "Zod" },
    ],
    description:
      "Multi-tenant assessment SaaS MVP for modern education — question banks, timed exams, analytics, certificates, billing, and full Arabic/English RTL support.",
    longDescription:
      "ExamFlow is a multi-tenant EdTech SaaS MVP for institutions and educators.",
    features: [
      "Multi-tenant organizations with role-based access",
      "Content hierarchy: Subjects → Topics → Lessons",
      "Question banks + Exam builder & timed exam engine",
      "Student Learn portal with lesson content",
      "Analytics dashboards & certificates",
      "Manual grading + autosave short answers",
      "Full EN/AR + RTL support",
      "Stripe billing + plan limits",
      "Email notifications",
      "White-label ready design system",
    ],
    challenges: [
      "Scalable multi-tenant architecture",
      "Full RTL layout and bilingual content",
      "Reliable exam engine with timing and grading",
      "Integrating billing, email, and role permissions",
    ],
    problems: [
      "Membership role as tenant source of truth",
      "Centralized i18n with design tokens",
      "Exam session state and server-side validation",
      "Stripe webhook handling",
    ],
    image: "/assets/projects images multi devices/15.png",
    live: "https://client-indol-beta-85.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/examflow-saas-platform",
  },
  {
    num: "08",
    slug: "gym-website",
    title: "Gym Website",
    category: "Fitness Website",
    tags: ["Frontend", "Landing", "React"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Swiper" },
      { name: "React" },
    ],
    description:
      "A modern gym website featuring class schedules, trainer profiles, and membership options.",
    longDescription:
      "A responsive fitness brand website focused on showcasing classes, trainers, and membership plans.",
    features: ["Responsive landing pages", "Trainer profiles", "Class schedules", "Membership sections"],
    challenges: ["Creating an energetic visual identity", "Keeping animations smooth on mobile"],
    problems: ["Used modular sections and Swiper for carousels", "Optimized assets for smaller screens"],
    image: "/assets/projects images multi devices/2.png",
    live: "https://mahmoudselsebaey.github.io/GYM/",
    github: "https://github.com/mahmoudselsebaey/GYM",
  },
  {
    num: "09",
    slug: "portfolio-app",
    title: "Elsebaey Portfolio",
    category: "Personal Portfolio",
    tags: ["Frontend", "Next.js", "React", "Portfolio", "Landing"],
    tools: [
      { name: "Next.js 15" },
      { name: "React 19" },
      { name: "TypeScript" },
      { name: "Tailwind CSS v4" },
      { name: "Framer Motion" },
      { name: "GSAP" },
      { name: "Radix UI" },
      { name: "MUI" },
      { name: "next-themes" },
      { name: "EmailJS" },
      { name: "AOS" },
      { name: "Swiper" },
    ],
    description:
      "Modern personal portfolio built with Next.js 15 App Router — dark/light themes, animated sections, project case studies, services, and contact form.",
    longDescription:
      "A production-ready personal portfolio powered by Next.js 15, React 19, TypeScript, and Tailwind CSS v4. Features dark/light mode (next-themes), Framer Motion & GSAP animations, Radix UI + MUI components, project case studies, services, recommendations, EmailJS contact form, SEO (sitemap, robots), and a polished design system.",
    features: [
      "Next.js 15 App Router + Turbopack",
      "Dark & light themes (next-themes)",
      "Framer Motion & GSAP animations",
      "Project case studies with dynamic routes",
      "Services, about, contact (EmailJS)",
      "SEO: sitemap, robots, Open Graph",
      "Radix UI + MUI + Tailwind design system",
    ],
    challenges: [
      "Building a distinctive personal brand",
      "Balancing rich animations with performance",
      "Structuring case studies and multi-page navigation",
    ],
    problems: [
      "App Router layouts with shared header/footer",
      "Theme tokens and next-themes integration",
      "Optimized image loading and motion preferences",
    ],
    image: "/assets/projects images multi devices/3.png",
    live: "https://mahmoud-elsebaey-portfolio.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/Elsebaey-Portfolio",
  },
  {
    num: "10",
    slug: "authentication-app",
    title: "Authentication App",
    category: "Full Stack Website",
    tags: ["Full Stack", "MERN", "Dashboard", "React", "Backend"],
    tools: [
      { name: "React" },
      { name: "Node.js" },
      { name: "Express" },
      { name: "MongoDB" },
      { name: "JWT" },
    ],
    description:
      "A full-stack authentication system with secure login, registration, and protected routes.",
    longDescription:
      "Complete auth flow with JWT, password hashing, and protected dashboard routes.",
    features: ["User registration & login", "JWT authentication", "Protected routes", "Password hashing"],
    challenges: ["Secure token handling", "Session management"],
    problems: ["HTTP-only cookies for tokens", "Middleware-based route protection"],
    image: "/assets/projects images multi devices/4.png",
    live: "https://authentication-app-frontend-seven.vercel.app/",
    github: "https://github.com/mahmoudSElsebaey/Authentication_app_Frontend",
  },
  {
    num: "11",
    slug: "sakney",
    title: "Sakney — سكني",
    category: "Rental Platform",
    tags: ["Frontend", "React", "Landing", "Real Estate"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "React" },
      { name: "Material UI" },
    ],
    description:
      "A rental platform helping expatriate students find suitable accommodation with search and filtering features.",
    longDescription:
      "Property rental UI focused on discovery and listing presentation for students.",
    features: ["Property listings", "Filter & search", "Responsive cards"],
    challenges: ["Clean listing layout"],
    problems: ["Material UI components for consistency"],
    image: "/assets/projects images multi devices/5.png",
    live: "https://mahmoudselsebaey.github.io/Sakney/",
    github: "https://github.com/mahmoudselsebaey/Sakney",
  },
  {
    num: "12",
    slug: "electronics-store",
    title: "Electronics Store",
    category: "E-commerce Website",
    tags: ["Frontend", "E-Commerce", "React", "Landing"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "Bootstrap" },
      { name: "Swiper" },
      { name: "JavaScript" },
      { name: "React" },
    ],
    description:
      "A simple e-commerce website showcasing electronic products with cart functionality.",
    longDescription:
      "Frontend electronics store with product grids and carousel promotions.",
    features: ["Product catalog", "Promotional carousels", "Responsive layout"],
    challenges: ["Product presentation"],
    problems: ["Bootstrap grid and Swiper carousels"],
    image: "/assets/projects images multi devices/6.png",
    live: "https://mahmoudselsebaey.github.io/Ecommerce_ReactJS/",
    github: "https://github.com/mahmoudSElsebaey/Ecommerce_ReactJS",
  },
  {
    num: "13",
    slug: "social-feed",
    title: "Social Feed",
    category: "Social Media SPA",
    tags: ["Frontend", "React", "Next.js"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React" },
      { name: "Next.js" },
    ],
    description:
      "A social media single-page application allowing users to create posts and interact with others.",
    longDescription:
      "Social feed interface built with React and Next.js.",
    features: ["Post feed", "Like interactions", "Responsive UI"],
    challenges: ["Feed layout and interactions"],
    problems: ["Component-based feed structure"],
    image: "/assets/projects-images/social-site.png",
    live: "#",
    github: "#",
  },
  {
    num: "14",
    slug: "sakney-dashboard",
    title: "Sakney Dashboard",
    category: "Admin Dashboard",
    tags: ["Dashboard", "Frontend"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "Bootstrap" },
      { name: "JavaScript" },
      { name: "Chart.js" },
    ],
    description:
      "An admin dashboard for managing rental listings, users, and platform analytics for Sakney.",
    longDescription:
      "Admin panel with analytics charts for property management.",
    features: ["Analytics charts", "Data tables", "Admin layout"],
    challenges: ["Dashboard information hierarchy"],
    problems: ["Chart.js for visualizations"],
    image: "/assets/projects images multi devices/7.png",
    live: "https://mahmoudselsebaey.github.io/SakneyDashboard/",
    github: "https://github.com/mahmoudselsebaey/SakneyDashboard",
  },
  {
    num: "15",
    slug: "game-warrior",
    title: "Game Warrior",
    category: "Gaming Website",
    tags: ["Frontend", "Landing", "Gaming", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Bootstrap" },
    ],
    description:
      "A gaming platform landing page highlighting featured games and releases.",
    longDescription:
      "Gaming brand landing page with hero and featured titles.",
    features: ["Hero section", "Featured games", "Responsive design"],
    challenges: ["Energetic gaming aesthetic"],
    problems: ["Bootstrap-based responsive layout"],
    image: "/assets/projects images multi devices/8.png",
    live: "https://mahmoudselsebaey.github.io/Game-Warrior/",
    github: "https://github.com/mahmoudselsebaey/Game-Warrior",
  },
  {
    num: "16",
    slug: "directory-ads",
    title: "Directory Ads",
    category: "Directory Website",
    tags: ["Frontend", "Landing", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
    ],
    description:
      "A directory and classified ads website template for listing businesses and services.",
    longDescription:
      "Directory-style landing page for ads and listings.",
    features: ["Listing grid", "Category sections"],
    challenges: ["Clear directory hierarchy"],
    problems: ["Semantic HTML structure"],
    image: "/assets/projects images multi devices/9.png",
    live: "https://mahmoudselsebaey.github.io/DirectoryAds/",
    github: "https://github.com/mahmoudselsebaey/DirectoryAds",
  },
  {
    num: "17",
    slug: "barber-shop",
    title: "Barber Shop",
    category: "Business Website",
    tags: ["Frontend", "Landing", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
    ],
    description:
      "A responsive barber shop website showcasing services, team, and booking information.",
    longDescription:
      "Local business landing page for a barber shop.",
    features: ["Services section", "Team profiles", "Contact CTA"],
    challenges: ["Matching brand tone"],
    problems: ["Clean section-based layout"],
    image: "/assets/projects images multi devices/10.png",
    live: "https://mahmoudselsebaey.github.io/Barber-Shop/",
    github: "https://github.com/mahmoudselsebaey/Barber-Shop",
  },
  {
    num: "18",
    slug: "amin-games",
    title: "Amin Games",
    category: "Gaming Portal",
    tags: ["Frontend", "Landing", "Gaming", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
    ],
    description:
      "A gaming portal landing page for a gaming platform highlighting featured games and releases.",
    longDescription:
      "A gaming platform landing page highlighting featured titles and upcoming releases.",
    features: ["Featured games", "Release highlights", "Responsive UI"],
    challenges: ["Showcasing multiple games clearly"],
    problems: ["Used structured grids and visual hierarchy"],
    image: "/assets/projects images multi devices/11.png",
    live: "https://mahmoudselsebaey.github.io/Amin-Games/",
    github: "https://github.com/mahmoudselsebaey/Amin-Games",
  },
  {
    num: "19",
    slug: "chairs-shop",
    title: "Chairs Shop",
    category: "Furniture Store",
    tags: ["Frontend", "Landing", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
    ],
    description:
      "An online furniture store showcasing different chair designs and products.",
    longDescription:
      "A simple furniture store frontend focused on product presentation and clean layout.",
    features: ["Product showcase", "Clean product cards"],
    challenges: ["Presenting products with minimal code and strong visuals"],
    problems: ["Relied on semantic HTML and careful CSS composition"],
    image: "/assets/projects images multi devices/12.png",
    live: "https://mahmoudselsebaey.github.io/chairs-shops/",
    github: "https://github.com/mahmoudselsebaey/chairs-shops",
  },
  {
    num: "20",
    slug: "wave-cafe",
    title: "Wave Cafe",
    category: "Coffee Shop Website",
    tags: ["Frontend", "Landing", "HTML/CSS/JS"],
    tools: [
      { name: "HTML5" },
      { name: "CSS3" },
    ],
    description:
      "A modern coffee shop website showcasing menu, services, and opening hours.",
    longDescription:
      "A modern cafe website with menu, services, and business information presented in a warm visual style.",
    features: ["Menu section", "Services", "Opening hours"],
    challenges: ["Matching cafe brand aesthetics"],
    problems: ["Used a calm layout with clear content sections"],
    image: "/assets/projects images multi devices/13.png",
    live: "https://mahmoudselsebaey.github.io/wave_cafe/",
    github: "https://github.com/mahmoudselsebaey/wave_cafe",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projectsData.find((p) => p.slug === slug);
}

export function getAllProjectSlugs(): string[] {
  return projectsData.map((p) => p.slug);
}

export const ALL_TAGS = [
  "SaaS",
  "MVP",
  "Full Stack",
  "Frontend",
  "Landing",
  "MERN",
  "React",
  "Next.js",
  "E-Commerce",
  "Dashboard",
  "News",
  "Portfolio",
  "Backend",
  "Gaming",
  "Real Estate",
  "RTL/LTR",
  "HTML/CSS/JS",
  "3D",
] as const;

export type ProjectTag = (typeof ALL_TAGS)[number];
